# Generated by Django 3.1.7 on 2021-03-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecard',
            old_name='ps_description',
            new_name='pc_description',
        ),
    ]
