# Generated by Django 3.1.7 on 2021-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='CSS class'),
        ),
    ]
