# Generated by Django 3.1.7 on 2021-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=255, verbose_name='Token')),
                ('tg_chat', models.CharField(max_length=200, verbose_name='Chat id')),
                ('tg_message', models.TextField(verbose_name='Text message')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
